package.json, src/CmapProcessor.coffee, src/glyph/Glyph.coffee, src/glyph/TTFGlyph.coffee, src/opentype/GPOSProcessor.coffee, src/opentype/GSUBProcessor.coffee, src/opentype/OpenTypeProcessor.coffee, src/subset/TTFSubset.coffee, src/tables/COLR.coffee, src/tables/GPOS.coffee, src/tables/GSUB.coffee, src/tables/cmap.coffee, src/tables/hmtx.coffee, src/tables/opentype.coffee, src/tables/vmtx.coffee
I added a `LazyArray` type, and a `lazy` pointer option to [restructure](https://github.com/devongovett/restructure), the library that fontkit uses to declaratively specify the sfnt tables. This allows data to be decoded only when needed rather than decoding the entire table up front, which improves performance dramatically for large fonts. Currently, I make use of it for the `cmap`, `hmtx`, `vmtx`, `GSUB`, and `GPOS` tables, which are usually the largest (besides the glyph paths themselves, which are already optimized). I see the biggest improvement for the `cmap` table, where there are often lots of subtables that we don't use, which we now also don't decode.
=> Performance Improvements

.gitignore, base.coffee, coverage.js, index.coffee, package.json, src/DFont.coffee, src/TTFFont.coffee, src/TrueTypeCollection.coffee, src/WOFF2Font.coffee, src/WOFFFont.coffee
Each supported font format is now a plugin to fontkit. Each format has a static probe method that returns whether or not the given buffer is in the format. This allows users to make custom builds supporting only the formats they need (good for browsers, etc.).
```javascript
// Get the default build with all supported formats loaded
var fontkit = require('fontkit');
// Get a build with no formats loaded
var fontkit = require('fontkit/base');
// Register a format
fontkit.registerFormat(require('fontkit/src/TTFFont'));
```
=> Make a plugin system for font formats

.travis.yml, package.json, src/aat/AATLayoutEngine.coffee, src/layout/LayoutEngine.coffee, src/opentype/GPOSProcessor.coffee, src/opentype/GSUBProcessor.coffee, src/opentype/OTLayoutEngine.coffee, src/opentype/OTProcessor.coffee, src/opentype/ShapingPlan.coffee, src/opentype/shapers/ArabicShaper.coffee, src/opentype/shapers/DefaultShaper.coffee, src/opentype/shapers/HangulShaper.coffee
This separates the OpenType and AAT shaping logic, and refactors the OpenType shapers.
The OT shapers now use a ShapingPlan object to store features to apply, and in which order to apply them. Features are grouped into stages, and each stage is processed separately. This allows shapers to control the order in which features are applied, and override the order defined by the font. The arabic shaper does this, and is necessary for some fonts where the defined order is wrong.
Also added Travis CI. 😀
=> Refactor OpenType shapers

package.json, src/glyph/TTFGlyph.js, src/glyph/TTFGlyphEncoder.js, src/subset/TTFSubset.js, test/subset.js
PDF viewers don’t support TrueType variation glyphs (gvar, avar, etc.), so we need to re-encode the post-processed variants into the subset instead of the original outlines.
The glyph encoder is generic: it takes a Path object and outputs a Buffer containing a TrueType glyph. We can eventually use it when producing fonts from scratch, as opposed to just subsetting.
=> Re-encode variation glyphs in PDF subsets

src/TTFFont.js, src/tables/feat.js, src/tables/fvar.js, src/tables/name.js
Instead of textual language names. Records in the name table are now arranged in the reverse order to how they were before.
Before:
`font.name.English.description`
After:
`font.name.description.en`
=> Use bcp-47 language codes in name table

src/CmapProcessor.js, src/TTFFont.js, src/aat/AATLayoutEngine.js, src/aat/AATLookupTable.js, src/aat/AATMorxProcessor.js, src/aat/AATStateMachine.js, src/decorators.js, src/glyph/TTFGlyph.js, src/layout/LayoutEngine.js, src/utils.js, test/glyph_mapping.js
Basically solves #56. Does the inverse of `font.layout`: it maps glyphs back to their input strings. This is complicated by ligatures and other substitutions. Currently, this supports AAT by viewing the state table as a graph, and doing a traversal over it to find inputs that produce a given glyph. It runs the state machine actions as it generates inputs. Obviously, things like loops in the state machine have to be ignored or an infinite number of strings would be produced.
Some AAT state tables (like [the one in Apple Color Emoji](https://cldup.com/AsISJp9XXO.png)) are really huge, so this is kinda slow. I added a bunch of caching for the lookup tables to speed it up a bit, and skip subtables that don't have the glyph id in their ligature lists. This type of operation should be much more …
=> Add support for getting string inputs from glyphs

src/TTFFont.js, src/aat/AATFeatureMap.js, src/aat/AATLayoutEngine.js, src/layout/GlyphRun.js, src/layout/LayoutEngine.js, src/opentype/OTLayoutEngine.js, src/opentype/OTProcessor.js, src/opentype/ShapingPlan.js, src/opentype/shapers/DefaultShaper.js, test/glyph_mapping.js
Along with support for passing an array of feature tags to `font.layout`, you can now pass an object with values explicitly set to false to disable those features if they were automatically applied by a shaper. This is to allow e.g. a UI to let the user control some feature behavior manually. 
Also passes back the script, language, and features that were selected as part of the resulting `GlyphRun`.
=> Allow user to override shaper features

src/WOFF2Font.js, test/glyphs.js
The end point of each contour is the cumulative sum of all previous values in the `nPoints` stream, not just the current one.
See https://www.w3.org/TR/WOFF2/#SimpleGlyph
Fixes https://github.com/devongovett/fontkit/issues/104
=> Fix decoding endPtsOfContours for WOFF2 glyphs

src/opentype/shapers/DefaultShaper.js, test/glyph_mapping.js
Don’t enter into infinite loop when no digits are found for numerator or denominator.
Fixes https://github.com/devongovett/fontkit/issues/123.
=> Make automatic fraction code a bit more robust

src/glyph/BBox.js, test/glyphs.js
A blank glyph will have an empty bbox (everything initialized to Infinity) and adding its bbox to the GlyphRun bbox will result in the later being all Infinity as well.
Fix this by checking for Infinity in BBox.addPoint(). Not sure if this is the best fix, alternatively we can add a BBox.isEmpty() or something similar and skip such boxes when calculating GlyphRun bbox.
Fixes https://github.com/devongovett/fontkit/issues/103
=> Fix bbox for GlyphRun with blank glyphs

.travis.yml
Building only with stable nodejs to cut the CI run time, I think testing other versions only on Linux is enough.
=> Enable CI on macOS

src/glyph/Glyph.js, src/opentype/GlyphInfo.js
If codePoints array in glyph constructor is empty then isMark attribute is true, which is wrong. CodePoints array may be empty if getGlyph method is called directly.
=> BUG FIX: Glyph isMark attribute is set to true when codepoints array is empty

src/subset/CFFSubset.js
Attempting to subset a CID-keyed CFF font with no subrs triggers a `TypeError` in CFFSubset.js because `subsetSubrs()` attempts to check the `.length` of null. This PR addresses that by not attempting to subset subrs at all if they do not exist in the font.
Fixes issue #42 (well, kinda but not really, the original issue that concerns is long gone but I found a related problem that should have been in a new issue). I didn't come up with this fix, credits go to @jahewson for pointing it out.
=> Fix subsetting CID fonts with no subrs

.travis.yml
Also removed the osx-specific retesting for Node "stable", which doesn't really add anything on top of the Node stable that already runs.
=> Update the CI node versions to reflect current LTS

src/tables/directory.js, test/directory.js
The spec for the searchRange and entrySelector specifies the following constraints:
>searchRange:	(Maximum power of 2 <= numTables) x 16
>entrySelector:	Log2(maximum power of 2 <= numTables)
>rangeShift:	NumTables x 16-searchRange
But the code was computing `searchRange` as just the power index, not the actual power of two that it should be.
Fixes #149 
Fixes #179
=> fix the entrySelector calculation

src/TTFFont.js
Setting the defaultLanguage allows you to overwrite the language returned by property getters like `fullName`, `familyName`, etc.
=> Added `defaultLanguage` to font objects

src/TTFFont.js, src/base.js, test/i18n.js
- As a follow-up to https://github.com/foliojs/fontkit/pull/194, this PR enables a global `fontkit.setDefaultLanguage(lang)` method.  
- Fonts will use the global language property, unless you explicitly override it via `font.setDefaultLanguage(lang)`
- If a font property isn't available in the given language, it will attempt to find a backup language to use.  For example, it will look for `defaultLanguage`, then `"en"`, then just whatever is first.
- Additionally, unit tests were added for `fontkit.setDefaultLanguage` as well as `font.setDefaultLanguage`
=> Set a global default language

src/subset/TTFSubset.js, src/tables/loca.js, test/subset.js
Fixes saving the loca index format when subsetting.
Fonts with version 1 (long format) were being saved with version 0.  This was mangling the odd offsets (they were being saved divided by two and read multiplied by two creating a off by one error)
Probably fixes https://github.com/bpampuch/pdfmake/issues/1659 and https://github.com/foliojs/pdfkit/issues/914
=> Fix saving loca index format/version when subsetting

package.json
Adds the repository entry with the github url to packages so that it appears on the npm page, making contributing easier.
=> Adding repository entry to packages json so that it appears on npm

README.md, src/aat/AATMorxProcessor.js, test/glyph_mapping.js
In a recent Chromium upgrade, ligatures were [disabled](https://bugs.chromium.org/p/chromium/issues/detail?id=896033&can=1&q=ligatures%20letter-spacing&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) when letterspacing was non-zero. In order to match this behavior, we needed to add the ability to disable default AAT morx features.
I've added a test for this case and validated it does allow us to disable ligatures with non-zero letterspacing but I'm not a font expert and want to validate this won't introduce any issues.
Here's a snippet
```typescript
let glyphRun;
if (characterSpacing === 0) {
glyphRun = fontkitFont.layout(text);
} else {
glyphRun = fontkitFont.layout(text, { liga: false });
}
```
and the resulting output
=> Augment AATMorxProcessor to allow for features to be disabled (instead of only enabled)

src/cff/CFFFont.js, test/glyphs.js
There's a logic error in the binary search that looks for fd index in `CFFFont#fdForGlyph` leading to erroneous result when gid is exactly equal to `range.first`.
To see the bug load a CID font like NotoSansCJKkr-Regular.otf in https://fontkit-demo.now.sh/ and try to draw character ":" (gid 27)
Its possible to optimize the binary search a bit but will let this for later, just get the minimal change to fix the bug
=> Fix getting the fd index for OTF/CFF CID fonts

src/cff/CFFTop.js, test/data/PingFang/LICENSE.txt, test/subset.js
Fix for FDArray parsing in CFF.
Related issues: https://github.com/bpampuch/pdfmake/issues/1961, https://github.com/foliojs/fontkit/issues/135
=> Fix for FDArray parsing in CFF

src/glyph/Path.js, test/glyphs.js
`new Function` is not allowed on sites with CSP.
=> Remove new Function call

src/opentype/shapers/index.js
Solved the "Type Error: Cannot read property 'syllable' of null" when a pdfmake document contains certain the characters \u0dda and \u0ddd. 
Reference: https://stackoverflow.com/questions/60056226/is-there-anyway-to-bypass-this-error-on-pdfmake-type-error-cannot-read-proper
=> Changed sinh's shaper into IndicShaper

package.json, src/tables/GPOS.js, src/tables/gvar.js, src/tables/just.js, src/tables/name.js
PR updated restructure to version 2.
Before merge is required:
- update babel - PR https://github.com/foliojs/fontkit/pull/196
Before release fonkit version for avoid CSP:
- release a new [restructure](https://github.com/foliojs/restructure) version with `new Function` fix (https://github.com/foliojs/restructure/pull/37)
@devongovett You can look at it?
=> Update restructure to v2

src/DFont.js, src/TrueTypeCollection.js
When using a .dfont on macOS (11.6), it seems like the postscriptName is of type Buffer instead of string, which leads to getFont failing and logging that an incorrect font is being used.
This is more of a workaround as ideally, the font's postscriptName should be consistent.
=> Support Buffer postscriptName

src/glyph/Path.js
This prevents the use of the transformed x instead of the original x when computing the transformed y.
=> fix Path.transform breaks Path rotation #268

src/tables/opentype.js, test/opentype.js
Added featureParams to get friendly stylistic set name via given nameID if given. 
For reference, see OT spec: https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-ss01---ss20
=> Added featureParams for friendly stylistic set names

src/subset/CFFSubset.js, test/subset.js
A little bit of context.
While working with pdfkit we found this error.
https://github.com/foliojs/pdfkit/issues/1106
We narrowed down the repro to fontkit with this little script
```
const fs = require('fs');
const notosans = require('fontkit').openSync('./NotoSansCJKsc-Bold.otf');
const subsetFor = (text, file) => {
const run = notosans.layout(text);
const subset = notosans.createSubset();
run.glyphs.forEach((glyph) => subset.includeGlyph(glyph));
subset.encodeStream().pipe(fs.createWriteStream(file));
};
subsetFor('间。楼', 'output.ttf');
```
With this script you can see that glyphs were missing on the subset font if you opened the font with something like fontforge
Regarding the logic behind this fix, when `!used_fds[fd]` was false, last items in `topDict.FDArray` and `used_subrs` …
=> Fix Noto font bug

src/glyph/CFFGlyph.js, test/issues.js
Fixes #282.
This branch fixes a ReferenceError that gets thrown when parsing certain fonts, including the Playfair Display font that is in the fontkit repository. The error started happening when version 1.9.0 of fontkit was released.
```
ReferenceError: Cannot access 'c3x' before initialization
```
The fix involved refactoring the `parse()` function to use block-scoping inside the switch case statements in that function. See [the MDN docs on redeclarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#redeclarations).
=> Fix reference error for certain fonts

src/encodings.js
fixing https://github.com/foliojs/fontkit/issues/284
=> fix: unsupported encodings for TextDecoder

package-lock.json
Bumps unicode-properties in `package-lock.json` so that we avoid the following errors:
```
Error: Cannot find module '.../fontkit/node_modules/unicode-properties/dist.main.cjs'
```
=> Bump unicode-properties

src/glyph/GlyphVariationProcessor.js
rounding after the delta interpolation instead of before prevents rounding issues leading do wrong value, e.g. in the unicode test suite case GVAR-9, column 4:
fixes #182
=> fix #182: apply rounding after delta interpolation
